### PR TITLE
Tabea

### PR DESCRIPTION
**Pull request by planatheisa**
issue #106

### CODE REVIEW

**Comment by sonofmun** [comment]
@planatheisa This looks like it deals with issues #104 #105 and #106 .  Is that correct?

**Comment by planatheisa** [comment]
Yes, that's correct.

**Comment by planatheisa** [comment]
Also added #81 just now.

**Comment by sonofmun** [comment]
OK.  Just make sure you mention all of the issues that you are dealing with in the comments on the pull request.

**Comment by planatheisa** [comment]
It seems you can't have more than one pull request open at the same time, so anything you add to your branch later on gets to the same pull request.

**Comment by sonofmun** [comment]
I think it is that you can only have one pull request for a certain 
branch, so if you add changes to your branch and push them, they will be 
added to the existing pull request for that branch.
And just whenever you add something to the same pull request that 
addresses a different issue, just add a comment that you are now dealing 
with that issue as opposed to the original issue.  That makes it easier 
to keep track.  And it will be easier to see what you are doing with 
each commit that you make.

On 16.11.2015 10:21, planatheisa wrote:
>
> It seems you can't have more than one pull request open at the same 
> time, so anything you add to your branch later on gets to the same 
> pull request.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenGreekAndLatin/csel-dev/pull/132#issuecomment-156964515>.
>

-- 
Matthew Munson
Researcher
Alexander von Humboldt Chair of Digital Humanities
Universität Leipzig, Institut für Informatik
Augustusplatz 10, 04109 Leipzig
Deutschland

**Pull request merged**
