### PR TITLE
Tabea

### PR DESCRIPTION
**Pull request by planatheisa**
This reverts commit 443bbd553f3a374caace7f0a7a49551a96182805.

Sorry about the revert revert. I didn’t find the “pull request” button. I hope this works. See description of commit for comments.

### CODE REVIEW

**Comment by sonofmun** [comment]
So what exactly happened here, Tabea?  Did you accidentally remove the changes that you made and then have to recreate them?

**Comment by planatheisa** [comment]
I'm not sure. I was commiting this from the Mac and I didn't find the option for the pull request, so I reverted it to add it from my Netbook (which had worked before). Then I suddenly saw the pull request thing, so I reverted the revert. And now I had changes (probably because I changed the bidirectional editing thing), so I commited them to my branch and again there is no pull request option. This is annoying.

**Comment by sonofmun** [comment]
It looks like all three of your commits are in this pull request, so everything should be fine.  I will merge it to master and then you can pull to your local master branch.
Are you still working on this file?  If not, I will change the refsDecl so that it should then pass the Hook test.

**Comment by planatheisa** [comment]
No, I'm done. It seems it automatically does a pull request when you commit something unlike on my Windows machine.

**Comment by planatheisa** [comment]
One question remains: What about the bidirectional editing option? Do I allow it or not? Does it change anything significantly?

**Comment by sonofmun** [comment]
Are you talking about bidirectional in Oxygen?  If so, I don't know because I don't use Oxygen.  This might be a better question for Annette or Simona.  As for now, I would not allow it since everything we are doing is left-to-right.

**Comment by planatheisa** [comment]
OK

**Comment by simonastoyanova** [comment]
It shouldn't change anything in your file, it's a settings thing, not an
editing-a-file thing (I think). But yeah, you don't need it for these
files.

On 13 November 2015 at 13:30, planatheisa <notifications@github.com> wrote:

> OK
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenGreekAndLatin/csel-dev/pull/77#issuecomment-156420330>
> .
>



-- 
Simona Stoyanova
Research Associate

Digital Humanities
Department of Computer Science
University of Leipzig
Augustusplatz 10
04109 Leipzig, Germany

**Pull request merged**
