### PR TITLE
issue 287

### PR DESCRIPTION
**Pull request by annettegessner**
tried alternative in xPath for paragraph OR line in level 2
(I used the xPath of [stoa0058.stoa001.opp-lat3.xml](https://github.com/OpenGreekAndLatin/csel-dev/blob/master/data/stoa0058/stoa001/stoa0058.stoa001.opp-lat3.xml) as a pattern.)

### CODE REVIEW

**Comment by sonofmun** [comment]
Well done! Merging now.

**Comment by annettegessner** [comment]
waaait

**Comment by sonofmun** [comment]
It passed. Everything is good.

**Comment by annettegessner** [comment]
strangely it passen, although I didn't change [@n='$3']) to [@n='$2']) ...

**Comment by sonofmun** [comment]
Change it and push it again.

**Pull request merged**
