### PR TITLE
Trailing space in URN attribute for stoa0040.054

### PR DESCRIPTION
**Pull request by PonteIneptique**

### CODE REVIEW

**Comment by sonofmun** [comment]
I think the `__cts__.xml` file needs to be changed as well. The file is now not found in the inventory.

**Comment by PonteIneptique** [comment]
What do you mean ?

**Comment by PonteIneptique** [comment]
Ok, the file name is actually `stoa0040.stoa054.opp-lat2 .xml` with a space and has `
<div type="edition" xml:lang="lat" n="urn:cts:latinLit:stoa0040.stoa054.opp-lat2 ">` with a space too.
Damn. Can you deal with it ?

**Comment by PonteIneptique** [comment]
Should be ok now @sonofmun

**Comment by sonofmun** [comment]
Everything is good now. Merging.

**Pull request merged**
