### PR TITLE
Changed two metadata files

### PR DESCRIPTION
**Pull request by sonofmun**
Two metadata files had the same edition repeated twice, which was messing up the word counts

### CODE REVIEW

**Comment by sonofmun** [comment]
Everything still passes. Please check and merge @planatheisa

**Comment by sonofmun** [comment]
Link to HookTest: http://ci.perseids.org/repo/OpenGreekAndLatin/csel-dev/d565a728-9640-4154-97dc-26bc0a1906fc

**Comment by planatheisa** [comment]
The `__cts__` does not have editor/publisher/year information in `description`. Does that matter here? Also, I have no idea what to make of `manifest.txt` and `result.json`.

**Comment by sonofmun** [comment]
Don't worry about the editor/publisher/year information right now. That would involve a wholesale change of the metadata files in this repo, and I am not ready to start with that yet.
And I have removed the manifest.txt and the results.json files. Those were relics of local testing I was doing for a new platform for HookTest.

**Comment by sonofmun** [comment]
Everything still passes: http://ci.perseids.org/repo/OpenGreekAndLatin/csel-dev/9a85295f-c1e4-49ea-bc26-1f748db7c0ed

**Pull request merged**
