### PR TITLE
Matt

### PR DESCRIPTION
**Pull request by sonofmun**
Fix for issue #186

### CODE REVIEW

**Comment by sonofmun** [comment]
Added another commit to bring in two volumes of Jerome's letters that I forgot to add before.

**Comment by annettegessner** [comment]
Hook is testing forever ... shall we merge now and check if those changes pass the hook test later?

**Comment by PonteIneptique** [comment]
Nope, you should wait for the result. Otherwise there is no point in the PR / Continuous Testing...

**Comment by PonteIneptique** [comment]
I assume Homer is currently used for something else actually...

**Comment by PonteIneptique** [comment]
@sonofmun Is there any good reason behind using "//" in your refsDecl ? Does not "/" simply works ?

**Comment by annettegessner** [comment]
Ok, then this has to wait until tomorrow. ;-)

**Comment by sonofmun** [comment]
@pontelneptique They were meant as a safeguard against requiring direct descent for all div elements. I plan to go through and systematically remove them and then go back and fix what is broken. I might get to it this week. We'll see.

**Comment by annettegessner** [comment]
Issue #186 can not be closed, stoa0292b.stoa001.opp-lat2.xml fails the hook test

**Pull request merged**
