### PR TITLE
Added missing resource for ant build

### PR DESCRIPTION
**Pull request by PonteIneptique**

### CODE REVIEW

**Comment by sonofmun** [comment]
What's up with the .DS_Store file.  Is that necessary?

**Comment by PonteIneptique** [comment]
It was already in there. Might as well keep it

**Comment by sonofmun** [comment]
I actually put .DS_Store into the .gitignore because it seemed to always cause problems with merging.  I think it is probably changed with almost every commit or other change and, thus, if two people work on two different files, it could be that the .DS_Store will conflict even though it is not important (I don't think).

**Comment by sonofmun** [comment]
I am going to merge this but then I am going to remove the .DS_Store file from the history to avoid problems in the future.

**Pull request merged**
