### PR TITLE
#219 and #220

### PR DESCRIPTION
**Pull request by annettegessner**

### CODE REVIEW

**Comment by annettegessner** [comment]
Merging files: 
Peter's solution for stoa0040.stoa011.opp-lat2
and
my (first) solution to stoa0292e.stoa001.opp-lat1

**Comment by annettegessner** [comment]
Don't forget to delete the following files after successful merging:
stoa0040.stoa011.opp-lat2.xml_volume_34_1
and 
stoa0292e.stoa001.opp-lat1_volume_49a

**Comment by annettegessner** [comment]
both passing hook test now

**Comment by sonofmun** [comment]
If you deleted them in your branch, then they will also be deleted in the master branch when I merge.  If you didn't delete them, then you can do that in your branch and do another pull request.

**Comment by annettegessner** [comment]
I know, thanks - this was a memo to myself ;-)

**Comment by annettegessner** [comment]
one last correction incoming

**Pull request merged**
