### PR TITLE
issue291 added xml:lang

### PR DESCRIPTION
**Pull request by annettegessner**
#291

### CODE REVIEW

**Comment by sonofmun** [comment]
Obviously not. This broke all of the files.

**Comment by sonofmun** [comment]
Sorry, it is because you didn't put an = sign after xml:lang

**Comment by annettegessner** [comment]
That's what happens, if you are in a hurry, you mess up the XML and message the wrong person. *sigh* Sorry, I was rushing to the Java Script tutorial, I'll fix this afterwards.

**Comment by annettegessner** [comment]
corrected and added correction stated by Thibault

**Comment by annettegessner** [comment]
wait a sec

**Comment by sonofmun** [comment]
That looks better.

**Comment by annettegessner** [comment]
aaand it's gone ;-) - no problem, thanks for merging

**Pull request merged**
